// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.yang.grpc.pb;

public interface ClientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.ClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
