// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.yang.grpc.pb;

public interface ClientReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.ClientReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
